### ISSUE TITLE
Coding Stylie

### ISSUE THREAD

**Issue by marcobiedermann** [chinchang/hint.css#127]
According to [Sass Guidelines](http://sass-guidelin.es/) you should:
- Use `//` comments everywhere
- NameFormat: Name of variable `hintSuccessColor` should be written in all lowercase letters with hyphens instead of underscores
- Indentation: Line should be indented with spaces, not tabs

**Comment by mendozagioo** [comment]
+1

**Comment by chinchang** [comment]
**Use `//` comments everywhere**

Quoting Sass Guidelines:
> When commenting a Sass-specific section, use Sass inline comments instead of a C-style block. This makes the comment invisible in the output, even in expanded mode during development.

Hence, where comments are required to be output in the final CSS, CSS style comments are used.

*   **NameFormat: Name of variable `hintSuccessColor` should be written in all lowercase letters with hyphens instead of underscores
*   Indentation: Line should be indented with spaces, not tabs**

These are just preferences.
