### ISSUE TITLE
Arrow border

### ISSUE THREAD

**Issue by onerkript** [chinchang/hint.css#88]
Hi, 

Thanks for this awesome plugin!

Now my issue : I'm trying to modify hint.css to add a border to the tooltip but I can't figure out how I should style the arrow. I'd like the whole tooltip to be white with a grey border. Can you help me out ?

Thanks in advance.

**Comment by chinchang** [comment]
Tried doing it and this is the closest I am able to reach: http://codepen.io/chinchang/pen/jPmbdM

The issue in giving border to the arrow is that the arrow is itself made up of borders. Way in which we can have borders for the arrow is by having another arrow placed behind it which is slightly bigger in size. But even this won't work here because we have already consumed both `after` and `before` pseudo elements.

**Comment by onerkript** [comment]
Yea, this is pretty much what I managed to come up with as well.

**Comment by joaocunha** [comment]
I think we should we improve the class names used to draw the border and arrow so they can be easily targeted, instead of writing cryptic `[data-hint]:after` overrides.

**Comment by chinchang** [comment]
@joaocunha Arrows (and tooltip body) are made using pseudo elements which cannot have classnames as they are not actual elements one writes in the markup. I guess thats a sort of tradeoff we'll have against the advantage of not having to write extra html to use Hint.css.
